redis:
  ## @section Redis image parameters
  image:
    ## @param image.tag Redis image tag
    tag: "8.2.1"
  ## @param replicaCount Number of Redis replicas to deploy
  replicaCount: 1

  auth:
    ## @param auth.enabled Enable Redis authentication
    enabled: true
    ## @param auth.password Redis password (if empty, random password will be generated)
    password: ""

  persistence:
    ## @param persistence.enabled Enable persistent storage
    enabled: true
    ## @param persistence.storageClass Storage class to use for persistent volume
    storageClass: ""
    ## @param persistence.accessMode Access mode for persistent volume
    accessMode: ReadWriteOnce
    ## @param persistence.size Size of persistent volume
    size: 8Gi

  ## @param resources Resource limits and requests for Redis pod
  #resources:
  #  limits:
  #    memory: 256Mi
  #  requests:
  #    cpu: 50m
  #    memory: 128Mi