mongodb:
  ## @section MongoDB image parameters
  image:
    ## @param image.tag MongoDB image tag
    tag: "8.0.13"

  ## @param replicaCount Number of MongoDB replicas to deploy
  replicaCount: 1

  auth:
    ## @param auth.enabled Enable MongoDB authentication
    enabled: true
    ## @param auth.rootUsername MongoDB root username
    rootUsername: admin
    ## @param auth.rootPassword MongoDB root password (if empty, random password will be generated)
    rootPassword: ""

  persistence:
    ## @param persistence.storageClass Storage class to use for persistent volume
    storageClass: ""
    ## @param persistence.accessMode Access mode for persistent volume
    accessMode: ReadWriteOnce
    ## @param persistence.size Size of persistent volume
    size: 8Gi
  
  ## @param resources Resource limits and requests for MongoDB pod
  #resources:
  #  limits:
  #    memory: 512Mi
  #  requests:
  #    cpu: 50m
  #    memory: 512Mi