deploymentstrategy: git
buildstrategy: plain
mainnamespace: kubero
registry:
  # Possible values: copy, create, none (default: create)
  # copy: Copy the secret from the main namespace
  # create: Create a new secret in the pipeline namespace
  # none: Do not create a secret
  createSecret: create
  host: missingregistry.mydomain.com/example
  username: admin
  password: admin
git:
  keys:
    created_at: "2022-09-21T20:51:57Z"
    id: 87654321
    priv: XXXXXXXXXXXXXXXXXX=
    pub: XXXXXXXXX=
    read_only: true
    title: bot@kubero
    url: https://api.github.com/repos/kubero-dev/template-nodeapp/keys/87654321
    verified: true
  repository:
    description: Simple example Node app
    id: 121212122
    name: template-nodeapp
    node_id: R_asdfasdfaa
    owner: kubero-dev
    private: true
    ssh_url: git@github.com:kubero-dev/template-nodeapp.git
  webhook:
    active: true
    created_at: "2022-06-21T19:37:07Z"
    events:
    - pull_request
    - push
    id: 123456789
    insecure: "0"
    url: https://somelocaladress.com/api/github/webhooks
name: example
phases:
- context: ""
  enabled: false
  name: review
- context: ""
  enabled: false
  name: test
- context: ""
  enabled: false
  name: stage
- context: ""
  enabled: true
  name: production
reviewapps: true
