postgres:
  ## @section PostgreSQL image configuration
  image:
    ## @param image.tag PostgreSQL image tag (immutable tags are recommended)
    tag: "17.6"

  ## @section Deployment configuration
  ## @param replicaCount Number of PostgreSQL replicas to deploy (Note: PostgreSQL doesn't support multi-master replication by default)
  replicaCount: 1

  ## @section PostgreSQL Authentication
  auth:
    ## @param auth.enablePostgresUser Enable/disable the postgres user
    enablePostgresUser: true
    ## @param auth.postgresPassword Password for the postgres admin user. If not set, a random password will be generated
    postgresPassword: ""
    ## @param auth.username Name for a custom user to create
    username: ""
    ## @param auth.password Password for the custom user to create
    password: ""
    ## @param auth.database Name for a custom database to create
    database: ""

  ## @section Resources
  resources: {}
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi

  ## @section Persistence
  persistence:
    ## @param persistence.enabled Enable persistence using Persistent Volume Claims
    enabled: true
    ## @param persistence.storageClass Persistent Volume storage class
    storageClass: ""
    ## @param persistence.size Persistent Volume size
    size: 8Gi
    ## @param persistence.accessModes Persistent Volume access modes
    accessModes:
      - ReadWriteOnce