{{- $name := .Values.name -}}
{{- $deploymentstrategy := .Values.deploymentstrategy -}}
{{- $deploykey := .Values.git.keys.priv -}}
{{- $deploykeyPub := .Values.git.keys.pub -}}
{{- $deploykeySshUrl := splitList ":" .Values.git.repository.ssh_url | first -}}

{{- range .Values.phases }}
{{- if .enabled }}
{{- if and (eq $deploymentstrategy "git") ($deploykeyPub) }}
apiVersion: v1
kind: Secret
metadata:
  name: "deployment-keys"
  namespace: {{ $name }}-{{ .name }}
  annotations:
    app.kubernetes.io/comment: "used by kuberoes Runpacks to pull the code"
type: Opaque
data:
  deploykey: {{ $deploykey | quote }}
  deploykey.pub: {{ $deploykeyPub | quote }}
---
{{- end }}
{{- end }}
{{- end }}