{{- $name := .Values.name -}}

{{- if and (eq .Values.deploymentstrategy "git") (eq .Values.registry.createSecret "copy") }}

{{- $mainnamespace := .Values.mainnamespace | default "kubero" -}}
{{- $secretObj := (lookup "v1" "Secret" $mainnamespace "registry-login") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $dockerconfigjson := (get $secretData ".dockerconfigjson") | default "ZW1wdHk=" }}
{{- $registryUsername := (get $secretData "username") | default "ZW1wdHk=" }}
{{- $registryPassword := (get $secretData "password") | default "ZW1wdHk=" }}


{{- range .Values.phases }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubero-pull-secret
  namespace: {{ $name }}-{{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ $name }}-{{ .name }}
  annotations:
    app.kubernetes.io/comment: "required by trivy to scan the image"
type: Opaque
data:
  username: {{ $registryUsername | quote }}
  password: {{ $registryPassword | quote }}
{{- end }}{{/* if .enabled */}}
{{- end }}{{/* end range .Values.phases */}}
{{- end }}{{/* if and (eq .Values.deploymentstrategy "git") (eq .Values.registry.createSecret "copy") */}}